// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pfa__.net.Data;

#nullable disable

namespace pfa__.net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("pfa__.net.Models.ConditionHistorique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_heure");

                    b.Property<int>("IdRegle")
                        .HasColumnType("int")
                        .HasColumnName("id_regle");

                    b.Property<string>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("auto")
                        .HasColumnName("source");

                    b.Property<string>("Valeur")
                        .HasColumnType("longtext")
                        .HasColumnName("valeur");

                    b.HasKey("Id");

                    b.HasIndex("IdRegle");

                    b.ToTable("condition_historique", (string)null);
                });

            modelBuilder.Entity("pfa__.net.Models.Equipement", b =>
                {
                    b.Property<int>("Id_Equipement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Equipement"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Etat")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Id_Piece")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("type_id")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.HasKey("Id_Equipement");

                    b.HasIndex("Id_Piece");

                    b.HasIndex("type_id");

                    b.ToTable("equipement");
                });

            modelBuilder.Entity("pfa__.net.Models.EquipementType", b =>
                {
                    b.Property<int>("id_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_type");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_type"));

                    b.Property<string>("Icon")
                        .HasColumnType("longtext")
                        .HasColumnName("icon");

                    b.Property<string>("Nom")
                        .HasColumnType("longtext")
                        .HasColumnName("nom");

                    b.HasKey("id_type");

                    b.ToTable("equipement_type");
                });

            modelBuilder.Entity("pfa__.net.Models.Piece", b =>
                {
                    b.Property<int>("Id_Piece")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_piece");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Piece"));

                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nom");

                    b.Property<int>("type_id")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.HasKey("Id_Piece");

                    b.HasIndex("type_id");

                    b.ToTable("piece");
                });

            modelBuilder.Entity("pfa__.net.Models.PieceType", b =>
                {
                    b.Property<int>("id_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_type");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_type"));

                    b.Property<string>("Icon")
                        .HasColumnType("longtext")
                        .HasColumnName("icon");

                    b.Property<string>("Nom")
                        .HasColumnType("longtext")
                        .HasColumnName("nom");

                    b.Property<string>("NomEn")
                        .HasColumnType("longtext")
                        .HasColumnName("nom_en");

                    b.Property<string>("NomFr")
                        .HasColumnType("longtext")
                        .HasColumnName("nom_fr");

                    b.HasKey("id_type");

                    b.ToTable("piece_type");
                });

            modelBuilder.Entity("pfa__.net.Models.Regle", b =>
                {
                    b.Property<int>("IdRegle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_regle");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRegle"));

                    b.Property<bool>("ChaqueJour")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("chaque_jour");

                    b.Property<DateTime?>("DateRegle")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dateRegle");

                    b.Property<string>("HeureDebut")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("heureDebut");

                    b.Property<string>("HeureFin")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("heureFin");

                    b.Property<int>("IdEquipement")
                        .HasColumnType("int")
                        .HasColumnName("id_equipement");

                    b.HasKey("IdRegle");

                    b.HasIndex("IdEquipement");

                    b.ToTable("regle", (string)null);
                });

            modelBuilder.Entity("pfa__.net.Models.ConditionHistorique", b =>
                {
                    b.HasOne("pfa__.net.Models.Regle", "Regle")
                        .WithMany("ConditionHistoriques")
                        .HasForeignKey("IdRegle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regle");
                });

            modelBuilder.Entity("pfa__.net.Models.Equipement", b =>
                {
                    b.HasOne("pfa__.net.Models.Piece", "Piece")
                        .WithMany("Equipements")
                        .HasForeignKey("Id_Piece")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pfa__.net.Models.EquipementType", "EquipementType")
                        .WithMany()
                        .HasForeignKey("type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipementType");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("pfa__.net.Models.Piece", b =>
                {
                    b.HasOne("pfa__.net.Models.PieceType", "PieceType")
                        .WithMany("Pieces")
                        .HasForeignKey("type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PieceType");
                });

            modelBuilder.Entity("pfa__.net.Models.Regle", b =>
                {
                    b.HasOne("pfa__.net.Models.Equipement", "Equipement")
                        .WithMany("Regles")
                        .HasForeignKey("IdEquipement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("pfa__.net.Models.Equipement", b =>
                {
                    b.Navigation("Regles");
                });

            modelBuilder.Entity("pfa__.net.Models.Piece", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("pfa__.net.Models.PieceType", b =>
                {
                    b.Navigation("Pieces");
                });

            modelBuilder.Entity("pfa__.net.Models.Regle", b =>
                {
                    b.Navigation("ConditionHistoriques");
                });
#pragma warning restore 612, 618
        }
    }
}
